# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 296ee1b2fa76de6d970e5486d25c18dee0edde1f0f09bb9b065d41c9d8bdad616145b8b160bd6e68ca3821804cd9394c8c4137d84fc5ff3cc1a6e8e30ea38503

test:
  secret_key_base: 6761bba055022702dfa330d178699fa0971cdf2b83032dc8b95b6ccbb521584d1f218421560dffb84091d50ca828bbe9a7c8e493bd4aaf967f74373f7fd32a98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
